// VARIANT 5 — Noir (Cold Ice)
// Near-black background with a desaturated ice-blue accent. Reads forensic,
// clinical, and confident. Pairs with Space Grotesk display + Geist Mono.

const VARIANT_NOIR = {
  id: "noir",
  name: "04 · Noir",
  subtitle: "Ice blue on graphite · Space Grotesk + Geist Mono",
  width: 1000,
  height: 760,
  notes: [
    "Accent: oklch(0.82 0.08 220) — desaturated ice blue. Feels forensic, not festive.",
    "Space Grotesk for display gives geometric authority without feeling corporate.",
    "Monochromatic cards with a single accent hairline — quieter than Phosphor, more modern than Amber.",
    "Best choice if you want to look like you ship advisories, not just blog posts.",
  ],
  theme: {
    body: "'Space Grotesk', system-ui, sans-serif",
    mono: "'Geist Mono', 'JetBrains Mono', monospace",
    bgDeep: "#0c0e12",
    bgSurface: "#14171c",
    navBg: "rgba(12,14,18,0.88)",
    heroBg: "#0c0e12",
    cardBg: "#12151b",
    terminalBg: "#090b0e",
    chromeBg: "#14171c",
    border: "#1f242c",
    textPrimary: "#e4ebf2",
    textSecondary: "#8a94a3",
    textMuted: "#576071",
    accent: "#8fc9e8",
    accentDim: "#6eaacf",
    cursor: "#8fc9e8",
    success: "#9ad6b0",
    badgeBg: "rgba(143,201,232,0.1)",
    pillBg: "rgba(143,201,232,0.06)",
    pillBorder: "rgba(143,201,232,0.3)",
    chromeRadius: 10,
    cardRadius: 8,
    terminalShadow: "0 0 80px rgba(143,201,232,0.05), 0 20px 40px rgba(0,0,0,0.5)",
    heroNameStyle: {
      fontFamily: "'Space Grotesk', system-ui, sans-serif",
      fontSize: 44, fontWeight: 600, lineHeight: 1.05,
      color: "#e4ebf2",
      letterSpacing: "-0.02em",
    },
    sectionTitleStyle: {
      fontFamily: "'Space Grotesk', system-ui, sans-serif",
      fontSize: 26, fontWeight: 600, color: "#e4ebf2",
      letterSpacing: "-0.015em",
    },
    btnPrimary: { background: "#8fc9e8", color: "#0c0e12", borderRadius: 6 },
    btnGhost: { background: "transparent", color: "#8a94a3", border: "1px solid #1f242c", borderRadius: 6 },
  },
};
window.VARIANT_NOIR = VARIANT_NOIR;
